# Generated by Django 2.2.17 on 2021-02-22 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_category_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('create_user', models.CharField(max_length=50, null=True, verbose_name='创建用户名称')),
                ('create_user_id', models.IntegerField(null=True, verbose_name='创建用户ID')),
                ('last_modifier_time', models.DateTimeField(auto_now=True, null=True, verbose_name='上次修改时间')),
                ('last_modifier_user', models.CharField(max_length=50, null=True, verbose_name='上次修改用户名称')),
                ('last_modifier_user_id', models.IntegerField(null=True, verbose_name='上次修改用户ID')),
                ('last_approval_time', models.DateTimeField(null=True, verbose_name='上次审阅时间')),
                ('last_approval_user', models.CharField(max_length=50, null=True, verbose_name='上次审阅用户名称')),
                ('last_approval_user_id', models.IntegerField(null=True, verbose_name='上次审阅用户ID')),
                ('delete_time', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('delete_user', models.CharField(max_length=50, null=True, verbose_name='删除用户名称')),
                ('delete_user_id', models.IntegerField(null=True, verbose_name='删除用户ID')),
                ('is_deleted', models.BooleanField(null=True, verbose_name='假删')),
                ('remark', models.CharField(max_length=500, null=True, verbose_name='备注')),
                ('category_id', models.IntegerField(null=True, verbose_name='分类id')),
                ('username', models.CharField(max_length=16, null=True, verbose_name='名字')),
                ('age', models.IntegerField(null=True, verbose_name='年纪')),
                ('edu_background', models.CharField(max_length=16, null=True, verbose_name='学历')),
                ('marital_status', models.CharField(max_length=16, null=True, verbose_name='婚姻状况')),
                ('native_place', models.CharField(max_length=16, null=True, verbose_name='籍贯')),
                ('height', models.FloatField(verbose_name='身高')),
                ('weight', models.FloatField(verbose_name='体重')),
                ('experience', models.IntegerField(verbose_name='经验')),
                ('work_status', models.CharField(max_length=16, null=True, verbose_name='工作状态')),
                ('information', models.TextField(default=None, null=True, verbose_name='更多信息')),
                ('training_record', models.TextField(default=None, null=True, verbose_name='培训记录')),
                ('work_record', models.TextField(default=None, null=True, verbose_name='工作记录')),
                ('servicesUrl', models.CharField(max_length=1000, null=True, verbose_name='地址')),
                ('grade', models.IntegerField(default=1, verbose_name='服务等级')),
                ('s_category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
            options={
                'verbose_name': '服务表',
                'verbose_name_plural': '服务表',
                'db_table': 'services',
            },
        ),
    ]
