# Generated by Django 2.2.17 on 2020-12-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('nickName', models.CharField(max_length=16, null=True, verbose_name='昵称')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('gender', models.IntegerField(default=0, verbose_name='性别')),
                ('avatarurl', models.TextField(null=True, verbose_name='头像地址')),
                ('token', models.CharField(blank=True, max_length=64, null=True, verbose_name='用户token')),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
    ]
