# Generated by Django 2.2.17 on 2020-12-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatarurl',
            field=models.CharField(max_length=1000, null=True, verbose_name='头像地址'),
        ),
    ]
