# Generated by Django 2.2.17 on 2020-12-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20201223_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='avatarurl',
            new_name='avatarUrl',
        ),
    ]
