# Generated by Django 2.2.17 on 2020-12-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_auto_20201223_1522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
