# Generated by Django 2.2.17 on 2021-04-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='is_grant',
            field=models.BooleanField(default=False, verbose_name='是否发放'),
        ),
    ]
