# Generated by Django 2.2.17 on 2021-04-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0002_auto_20210417_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='money',
            field=models.FloatField(default=0, verbose_name='赏金总数'),
        ),
    ]
