# Generated by Django 2.2.17 on 2021-04-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0003_auto_20210417_1334'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reward',
            table='reward',
        ),
    ]
