# Generated by Django 2.2.17 on 2021-04-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0004_auto_20210417_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='total_money',
            field=models.FloatField(default=0, verbose_name='赏金总数'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='money',
            field=models.FloatField(default=0, verbose_name='为发放赏金总数'),
        ),
    ]
