# Generated by Django 2.2.17 on 2021-02-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210131_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='create_user',
            field=models.CharField(max_length=50, null=True, verbose_name='创建用户名称'),
        ),
        migrations.AddField(
            model_name='cart',
            name='create_user_id',
            field=models.IntegerField(null=True, verbose_name='创建用户ID'),
        ),
        migrations.AddField(
            model_name='cart',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='cart',
            name='delete_time',
            field=models.DateTimeField(null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='cart',
            name='delete_user',
            field=models.CharField(max_length=50, null=True, verbose_name='删除用户名称'),
        ),
        migrations.AddField(
            model_name='cart',
            name='delete_user_id',
            field=models.IntegerField(null=True, verbose_name='删除用户ID'),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_deleted',
            field=models.BooleanField(null=True, verbose_name='假删'),
        ),
        migrations.AddField(
            model_name='cart',
            name='last_approval_time',
            field=models.DateTimeField(null=True, verbose_name='上次审阅时间'),
        ),
        migrations.AddField(
            model_name='cart',
            name='last_approval_user',
            field=models.CharField(max_length=50, null=True, verbose_name='上次审阅用户名称'),
        ),
        migrations.AddField(
            model_name='cart',
            name='last_approval_user_id',
            field=models.IntegerField(null=True, verbose_name='上次审阅用户ID'),
        ),
        migrations.AddField(
            model_name='cart',
            name='last_modifier_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='上次修改时间'),
        ),
        migrations.AddField(
            model_name='cart',
            name='last_modifier_user',
            field=models.CharField(max_length=50, null=True, verbose_name='上次修改用户名称'),
        ),
        migrations.AddField(
            model_name='cart',
            name='last_modifier_user_id',
            field=models.IntegerField(null=True, verbose_name='上次修改用户ID'),
        ),
        migrations.AddField(
            model_name='cart',
            name='remark',
            field=models.CharField(max_length=500, null=True, verbose_name='备注'),
        ),
    ]
