# Generated by Django 2.2.17 on 2021-02-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210201_1108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
