# Generated by Django 2.2.17 on 2021-02-22 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='权限名称')),
                ('code', models.CharField(max_length=10, null=True, verbose_name='权限编码')),
            ],
            options={
                'verbose_name': '权限信息',
                'verbose_name_plural': '权限信息',
                'db_table': 'syspermission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('create_user', models.CharField(max_length=50, null=True, verbose_name='创建用户名称')),
                ('create_user_id', models.IntegerField(null=True, verbose_name='创建用户ID')),
                ('last_modifier_time', models.DateTimeField(auto_now=True, null=True, verbose_name='上次修改时间')),
                ('last_modifier_user', models.CharField(max_length=50, null=True, verbose_name='上次修改用户名称')),
                ('last_modifier_user_id', models.IntegerField(null=True, verbose_name='上次修改用户ID')),
                ('last_approval_time', models.DateTimeField(null=True, verbose_name='上次审阅时间')),
                ('last_approval_user', models.CharField(max_length=50, null=True, verbose_name='上次审阅用户名称')),
                ('last_approval_user_id', models.IntegerField(null=True, verbose_name='上次审阅用户ID')),
                ('delete_time', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('delete_user', models.CharField(max_length=50, null=True, verbose_name='删除用户名称')),
                ('delete_user_id', models.IntegerField(null=True, verbose_name='删除用户ID')),
                ('is_deleted', models.BooleanField(null=True, verbose_name='假删')),
                ('remark', models.CharField(max_length=500, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=50, verbose_name='角色名称')),
                ('status', models.IntegerField(default=1, verbose_name='角色状态')),
                ('need_approval', models.BooleanField(default=True, verbose_name='是否需要审核')),
                ('operator_time', models.DateTimeField(null=True, verbose_name='操作时间')),
                ('operator_user', models.CharField(max_length=50, null=True, verbose_name='操作人')),
                ('operator_user_id', models.IntegerField(null=True, verbose_name='操作人id')),
                ('permissions', models.ManyToManyField(to='user.Permission', verbose_name='拥有的所有权限')),
            ],
            options={
                'verbose_name': '角色表',
                'verbose_name_plural': '角色表',
                'db_table': 'sysrole',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('create_user', models.CharField(max_length=50, null=True, verbose_name='创建用户名称')),
                ('create_user_id', models.IntegerField(null=True, verbose_name='创建用户ID')),
                ('last_modifier_time', models.DateTimeField(auto_now=True, null=True, verbose_name='上次修改时间')),
                ('last_modifier_user', models.CharField(max_length=50, null=True, verbose_name='上次修改用户名称')),
                ('last_modifier_user_id', models.IntegerField(null=True, verbose_name='上次修改用户ID')),
                ('last_approval_time', models.DateTimeField(null=True, verbose_name='上次审阅时间')),
                ('last_approval_user', models.CharField(max_length=50, null=True, verbose_name='上次审阅用户名称')),
                ('last_approval_user_id', models.IntegerField(null=True, verbose_name='上次审阅用户ID')),
                ('delete_time', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('delete_user', models.CharField(max_length=50, null=True, verbose_name='删除用户名称')),
                ('delete_user_id', models.IntegerField(null=True, verbose_name='删除用户ID')),
                ('is_deleted', models.BooleanField(null=True, verbose_name='假删')),
                ('remark', models.CharField(max_length=500, null=True, verbose_name='备注')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('nickName', models.CharField(max_length=16, null=True, verbose_name='昵称')),
                ('username', models.CharField(max_length=16, null=True, verbose_name='真实姓名')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('gender', models.IntegerField(default=0, verbose_name='性别')),
                ('avatarUrl', models.CharField(max_length=1000, null=True, verbose_name='头像地址')),
                ('loginTime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登录时间')),
                ('is_vistor', models.BooleanField(default=True)),
                ('roles', models.ManyToManyField(db_table='sysuser_roles', max_length=50, to='user.Role', verbose_name='角色')),
                ('service', models.ManyToManyField(db_constraint=False, db_table='user_service', to='service.Services', verbose_name='服务')),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('userInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
            options={
                'verbose_name': '用户token信息',
                'verbose_name_plural': '用户token信息',
                'db_table': 'sysuser_token',
            },
        ),
    ]
