# Generated by Django 2.2.17 on 2021-01-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210105_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='service',
            field=models.ManyToManyField(db_table='user_service', to='user.Services', verbose_name='服务'),
        ),
    ]
