# Generated by Django 2.2.17 on 2021-01-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_services_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='servicesUrl',
            field=models.CharField(max_length=1000, null=True, verbose_name='地址'),
        ),
    ]
