# Generated by Django 2.2.17 on 2021-01-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210107_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='grade',
            field=models.IntegerField(default=1, verbose_name='服务等级'),
        ),
    ]
