# Generated by Django 2.2.17 on 2021-01-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_services_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='username',
            field=models.CharField(max_length=16, null=True, verbose_name='名字'),
        ),
    ]
