# Generated by Django 2.2.17 on 2021-02-02 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='service',
            field=models.ForeignKey(db_column='good', db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to='user.Services'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='good_id',
            field=models.IntegerField(),
        ),
    ]
