# Generated by Django 2.2.17 on 2021-02-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210202_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='good_price',
            field=models.FloatField(default=None),
        ),
    ]
