# Generated by Django 2.2.17 on 2021-02-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_cart_good_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='is_select',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
