# Generated by Django 2.2.17 on 2021-02-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210202_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='good_price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='is_select',
            field=models.BooleanField(default=True),
        ),
    ]
