# Generated by Django 2.2.17 on 2021-02-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='OrderNumber',
            field=models.CharField(default=None, max_length=512, verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ManyToManyField(db_table='order_address', default=None, to='address.Address', verbose_name='配送地址'),
        ),
    ]
