# Generated by Django 2.2.17 on 2021-03-01 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210226_1551'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='orderservice',
            table='order_service',
        ),
    ]
