# Generated by Django 2.2.17 on 2021-03-01 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_address_is_default'),
        ('order', '0003_auto_20210301_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='address.Address', verbose_name='配送地址'),
        ),
    ]
