# Generated by Django 2.2.17 on 2021-05-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderservice_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_complian',
            field=models.BooleanField(default=False, verbose_name='是否投诉'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_evaluate',
            field=models.BooleanField(default=False, verbose_name='是否评价'),
        ),
    ]
